### PR TITLE
Fix findBookmarks: Return empty tags if none found

### LINKED ISSUE #371: REST: Bookmark with no tags contains empty tag
Bookmarks that do not have a tag now return an empty "" tag when trying to tags:
```
"tags": [
  ""
]
```

### Call
GET `http://msi-7816:8080/index.php/apps/bookmarks/public/rest/v2/bookmark`

### Replay
```
{
  "data": [
    {
      "id": "17",
      "url": "http://asdf.com",
      "title": "asdf",
      "user_id": "admin",
      "description": "",
      "public": "0",
      "added": "1495714580",
      "lastmodified": "1495714580",
      "clickcount": "0",
      "tags": [
        ""
      ]
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by marcelklehr**
fixes #371

### CODE REVIEW

File: controller/lib/bookmarks.php [hunk 1]
```diff
@@ -226,7 +226,11 @@ public function findBookmarks(
 		$bookmarks = array();
 		foreach ($results as $result) {
 			if ($returnTags) {
-				$result['tags'] = explode(',', $result['tags']);
+				if ($result['tags'] != "") {
```
Comment (blizzz) [inline controller/lib/bookmarks.php]: please always use strict comparison (e.g. ``!==``). This won't work then, because ``$result['tags']`` is null. Also, not formatting is not enough, because an array is expected.

The one liner can be kept, but with a condition:

```php
$result['tags'] = is_null($result['tags']) ? [] : explode(',', $result['tags']);
```

or the longer version with full if-condition:

```php
if($result['tags'] === null) {
	$result['tags'] = [];
} else {
	$result['tags'] = explode(',', $result['tags']);
}
```

**Review by blizzz — DISMISSED** [review]

**Comment by blizzz** [comment]
ah, let me push directly :)

**Comment by blizzz** [comment]
@marcelklehr pushed my changes. If you agree and tests run, please merge.

File: controller/lib/bookmarks.php [hunk 2]
```diff
@@ -226,7 +226,7 @@ public function findBookmarks(
 		$bookmarks = array();
 		foreach ($results as $result) {
 			if ($returnTags) {
-				$result['tags'] = explode(',', $result['tags']);
+				$result['tags'] = is_null($result['tags']) ? [] : explode(',', $result['tags']);
```
Comment (marcelklehr) [inline controller/lib/bookmarks.php]: `$result['tags']` is never null, though. See line 195: `$qb->createFunction("array_to_string(array_agg(" . $qb->getColumnName('t.tag') . "), ',')"), 'tags'...`

This should be `$result['tags'] === '' ?`, imo, don't you think?

**Review by marcelklehr — COMMENTED** [review]
Change is regression

File: controller/lib/bookmarks.php (hunk 1 above)
Comment (marcelklehr) [inline controller/lib/bookmarks.php]: $result['tags'] is not an array, that's why this loop exists in the first place ;)

File: controller/lib/bookmarks.php (hunk 2 above)
Comment (blizzz) [inline controller/lib/bookmarks.php]: I went with the debugger through it, and it was clearly a null. However, Postgres tests were failing exactly here. Do you work against Postgres?

i'll have another look anyhow, thx!

Comment (blizzz) [inline controller/lib/bookmarks.php]: Two lines further you have the functions used for the other RDBMs, so it seems to be DB-realted indeed. I included now an empty string in the condition and turned it into the ``if``, because it got too long.

**Comment by marcelklehr** [comment]
Thanks for clearing that up :) Good to go!
