### PR TITLE
Use query builder

### LINKED ISSUE #305: TAG rename doesn't work
### Steps to reproduce
1. Create a bookmark
2. Add a tag to the bookmark
3. Edit the tag changing its name

### Expected behaviour
The tag get renamed

### Actual behaviour
Nothing happens.
An error is printed in nextcloud.log

### Server configuration
**Operating system**: debian 8

**Web server:** apache2 v2.4

**Database:** mariadb 10.0.28

**PHP version:** 5.6.27

**nextcloud version:** 10.0.1

**Bookmarks version:** 0.9.0

**Updated from an older nextcloud or fresh install:** fresh

**Where did you install ownCloud from:**

I attach nextcloud.log with the specific error.
[nextcloud.log.zip](https://github.com/nextcloud/bookmarks/files/594023/nextcloud.log.zip)

### PR DESCRIPTION
**Pull request by marcelklehr**
This is a work in progress, I've added you as a collaborator so you can also push to the branch @blizzz ;)

This will hopefully also fix #305

### CODE REVIEW

File: controller/lib/bookmarks.php [hunk 1]
```diff
@@ -72,25 +72,23 @@ public function __construct(
...
-		$tags = $query->fetchAll();
+    		$qb->where($qb->expr()->notIn('tag', $filterTags));
+    	}
+		$qb
+		->groupBy('tag')
+		->orderBy('nbr', 'DESC')
+		->setFirstResult($offset)
+		->setMaxResults($limit);
+		$qb->setParameter(':user_id', $userId);
+    	$tags = $qb->execute()->fetchAll();
```
Comment (marcelklehr) [inline controller/lib/bookmarks.php]: Not sure this will work. Pls, correct, if not :)

File: controller/lib/bookmarks.php [hunk 2]
```diff
@@ -72,25 +72,23 @@ public function __construct(
...
 	 */
 	public function findTags($userId, $filterTags = [], $offset = 0, $limit = -1) {
-		$params = array_merge($filterTags, $filterTags);
-		array_unshift($params, $userId);
-		$notIn = '';
+		$qb = $this->db->getQueryBuilder();
+		$qb->automaticTablePrefix(true);
+		$qb
+		->select('tag', $qb->createFunction('COUNT(*)'))
+		->selectAlias('COUNT(*)', 'nbr')
```
Comment (marcelklehr) [inline controller/lib/bookmarks.php]: This doesn't do what it's supposed to:
```
    0 => Array (
         'tag' => 'cloud'
-        'nbr' => 1
+        'nbr' => 'COUNT(*)'
+        'COUNT(*)' => '1'
```

File: controller/lib/bookmarks.php [hunk 3]
```diff
@@ -397,35 +416,45 @@ public function editBookmark($userid, $id, $url, $title, $tags = [], $descriptio
...
-		$result = $query->execute($params);
 
+		$qb = $this->db->getQueryBuilder();
+		$qb->automaticTablePrefix(true);
+		$qb
+		->update('bookmarks', 'bm')
+		->set('bm.url', ':url')
+		->set('bm.title', ':title')
+		->set('bm.public', ':public')
+		->set('bm.description', ':description')
```
Comment (marcelklehr) [inline controller/lib/bookmarks.php]: How is one supposed to supply values here? https://github.com/nextcloud/server/blob/master/lib/private/DB/QueryBuilder/QueryBuilder.php#L660 says parameters are allowed, but [apparently this doesn't work](https://travis-ci.org/nextcloud/bookmarks/jobs/197972122#L395).
Supplying values directly also doesn't work, because they're quoted like column names (see the url value): https://travis-ci.org/nextcloud/bookmarks/jobs/197803504#L395

Comment (marcelklehr) [inline controller/lib/bookmarks.php]: opened https://github.com/nextcloud/server/issues/3373 for this

File: controller/lib/bookmarks.php [hunk 4]
```diff
@@ -315,47 +328,37 @@ public function deleteUrl($userId, $id) {
...
-
-			$params = [$new, $old, $userId];
-			$query->execute($params);
-		}
+		// Remove potentially duplicated tags
+		$qb = $this->db->getQueryBuilder();
+		$qb->automaticTablePrefix(true);
+		$qb
+		->delete('bookmarks_tags', 'tgs')
+		->innerJoin('bm', 'bookmarks', 'tgs.bookmark_id = bm.id')
```
Comment (marcelklehr) [inline controller/lib/bookmarks.php]: Mmh, a quick search spit out these, though: [[1]](https://stackoverflow.com/questions/2114534/mysql-syntax-for-join-update/2114583#2114583) [[2]](https://stackoverflow.com/questions/652770/delete-with-join-in-mysql#4192849)

**Comment by blizzz** [comment]
> This is a work in progress, I've added you as a collaborator so you can also push to the branch @blizzz ;)

Ty! As contributor, you should also be able to create and push to branches within the bookmark repo.

**Comment by blizzz** [comment]
I have some fixes, will add more and push later, but first kiddo wants to jump out of the bathtub ;)

**Comment by blizzz** [comment]
Pushed, essentially it is how you passed the parameters. There are also some style issues, e.g. indentation, and we use the short way for arrays, etc.

I did not do a complete review yet, but the tests should pass now.

**Comment by blizzz** [comment]
> but the tests should pass now.

so much about the theory… locally they pass…

**Comment by blizzz** [comment]
@marcelklehr in a nutshell, every comparison should go through the expression builder. E.g.

```php
->where('tgs.tag = :tag')
```

would be

```php
->where($qb->expr()->eq('tag', $qb->createNamedParameter($old))
```

Or  ``createParameter('name')``  instead of ``createNamedParameter``, which i used in my commit.

This causes most problems. Would you have the time to change this accordingly?

**Comment by marcelklehr** [comment]
Thanks! Ah, ok, I will change that

**Comment by marcelklehr** [comment]
All tests pass, now, except for owncloud master! :tada:

File: controller/lib/bookmarks.php [hunk 5]
```diff
@@ -315,47 +316,28 @@ public function deleteUrl($userId, $id) {
...
+			->andWhere($qb->expr()->eq('t.tag', $qb->createNamedParameter($old)));
+		$qb->execute();
+
+		// Update tags to the new label
+		$qb = $this->db->getQueryBuilder();
+		$qb->automaticTablePrefix(true);
+		$qb
+			->update('bookmarks_tags', 'tgs')
+			->set('tgs.tag', $qb->createNamedParameter($new))
+			->innerJoin('bm', 'bookmarks', 'tgs.bookmark_id = bm.id')
```
Comment (marcelklehr) [inline controller/lib/bookmarks.php]: Not allowed by mysql or not allowed by the query builder?

File: controller/lib/bookmarks.php [hunk 6]
```diff
@@ -397,35 +376,34 @@ public function editBookmark($userid, $id, $url, $title, $tags = [], $descriptio
...
 
+		$qb = $this->db->getQueryBuilder();
+		$qb->automaticTablePrefix(true);
+		$qb
+			->update('bookmarks')
+			->set('url', $qb->createNamedParameter(htmlspecialchars_decode($url)))
+			->set('title', $qb->createNamedParameter(htmlspecialchars_decode($title)))
+			->set('public', $qb->createNamedParameter($isPublic))
+			->set('description', $qb->createNamedParameter(htmlspecialchars_decode($description)))
+			->set('lastmodified', $qb->createFunction('UNIX_TIMESTAMP()'))
```
Comment (marcelklehr) [inline controller/lib/bookmarks.php]: Tests seem to pass for all. For SQLite this is [automatically translated](https://travis-ci.org/nextcloud/bookmarks/jobs/200094785#L394) to "strftime('%s','now')"

**Comment by marcelklehr** [comment]
@blizzz re pushing to branches: In fact, being a contributor in github's terms just means that I authored commits that ended up in a branch in the main repo, not necessarily that I have permission to push new ones myself ;)

**Comment by blizzz** [comment]
great work @marcelklehr i try to give it a final look tonight

File: controller/lib/bookmarks.php [hunk 7]
```diff
@@ -457,46 +421,70 @@ public function addBookmark($userid, $url, $title, $tags = array(), $description
...
-			$query->execute($params);
+
+			$qb
+				->where($qb->expr()->like('url', $qb->createParameter('compareUrl'))) // Find url in the db independantly from its protocol
+				->andWhere($qb->expr()->eq('user_id', $qb->createParameter('userID')));
+				$qb->setParameters([
+					'userID' => $userid,
+					'url' => $decodedUrl,
+					'compareUrl' => '%' . $this->db->escapeLikeParameter($decodedUrlNoPrefix),
+					'title' => $title,
```
Comment (marcelklehr) [inline controller/lib/bookmarks.php]: Should $title be htmlspecialchars_decode`d here, too, like on L480?

File: controller/lib/bookmarks.php [hunk 8]
```diff
@@ -230,44 +235,35 @@ public function findBookmarks(
...
-					$sql .= ' AND lower( concat(url,title,description,IFNULL(tags,\'\') )) like ? ';
-				} else {
-					$sql .= ' AND lower(url || title || description || IFNULL(tags,\'\') ) like ? ';
+		$filterExpressions = [];
+		$otherColumns = ['b.url', 'b.title', 'b.description'];
+		foreach ($filters as $filter) {
+			$filterExpressions[] = $qb->expr()->eq('t.tag', $qb->createNamedParameter($filter));
+			if (!$filterTagOnly) {
+				foreach ($otherColumns as $col) {
+					$filterExpressions[] = $qb->expr()->like($qb->createFunction('lower(' . $qb->getColumnName($col) . ')',
```
Comment (blizzz) [inline controller/lib/bookmarks.php]: ``like`` misses parameters

Comment (blizzz) [inline controller/lib/bookmarks.php]: tests succeed, but I find it suspicious, perhaps a misplaced bracket? Could you check?

File: controller/lib/bookmarks.php [hunk 9]
```diff
@@ -166,58 +170,59 @@ public function findBookmarks(
...
+			$qb->setMaxResults($limit);
+			if ($offset != null) {
+				$qb->setFirstResult($offset);
+			}
 		}
 
-		$query = $this->db->prepare($sql, $limit, $offset);
-		$query->execute($params);
-		$results = $query->fetchAll();
+		$results = $qb->execute()->fetchAll();
```
Comment (blizzz) [inline controller/lib/bookmarks.php]: the query does not return bookmarks without tags

File: controller/lib/bookmarks.php (hunk 7 above)
Comment (blizzz) [inline controller/lib/bookmarks.php]: Seems to work either way for me. Leave it out then 🤷

File: controller/lib/bookmarks.php [hunk 10]
```diff
@@ -230,44 +235,35 @@ public function findBookmarks(
...
 				}
-				$params[] = '%' . strtolower($filter) . '%';
 			}
 		}
+		if ($connectWord == 'AND') {
+			$filterExpression = call_user_func_array([$qb->expr(), 'andX'], $filterExpressions);
+		}else {
+			$filterExpression = call_user_func_array([$qb->expr(), 'orX'], $filterExpressions);
+		}
+		$qb->andWhere($filterExpression);
```
Comment (marcelklehr) [inline controller/lib/bookmarks.php]: ahh, this is the offending line. It should only be run, if there actually are any filters :)

**Comment by marcelklehr** [comment]
I couldn't find anything wrong with the editBookmark or addTags methods, so I suspect findBookmarks' aggregate function is behaving wrongly and every bookmark is getting all tags. Can you confirm that?

File: controller/lib/bookmarks.php (hunk 8 above)
Comment (marcelklehr) [inline controller/lib/bookmarks.php]: the brackets are a bit confusing here :) the statement continues on the next line. That's where the second parameter is ;)

Comment (blizzz) [inline controller/lib/bookmarks.php]: Sure, however ``createFunction`` is not closed here.

File: controller/lib/bookmarks.php (hunk 10 above)
Comment (marcelklehr) [inline controller/lib/bookmarks.php]: Fixed above: https://github.com/nextcloud/bookmarks/pull/332/files#diff-60bf617da66ab938849bb119ba377bc5R249

**Comment by marcelklehr** [comment]
Once you say it's good to go, I'll squash these (unless you're doing a squash merge anyway?)

**Comment by marcelklehr** [comment]
Found the bug in editBookmark and fixed it. I also expanded the associated test case to catch this kind of error in the future.

**Comment by blizzz** [comment]
https://github.com/nextcloud/bookmarks/pull/332#discussion_r101903132

This is still an issue. To reproduce:
1. Add a bookmark (do not assign any tags)
2. → it will appear on the list
3. Reload → It is missing

**Comment by marcelklehr** [comment]
@blizzz ah, sorry I misinterpreted that comment and inadvertently found a different bug :'D The problem was an inner join instead of a left join. Fixed and expanded test case.

The new renameTag test fails now.

**Comment by marcelklehr** [comment]
Fixed renameTag.

**Comment by blizzz** [comment]
It's getting better and better, I am really excited :)

One more thing however

1. Have two bookmarks A and B with tags "tag1 tag2" for A and "tag1" for B.
2. Filter for "tag1"
→ Only "tag1" is shown for Bookmark A, but all are expected.

**Comment by marcelklehr** [comment]
I'm excited, too :D 
That tags bug should be fixed now.

**Comment by marcelklehr** [comment]
@nickvergessen Are you a maintainer as well? In that case could you take a look at it again?

**Comment by blizzz** [comment]
@marcelklehr [this](https://github.com/nextcloud/bookmarks/pull/332#issuecomment-284267090) is fixed, however when when I filter for two tags, the results do not shop up.  For example:

Have a bookmark with tags "tag1" "tag2". Filter for "tag1" → it is shown. Filter additionally for "tag2" → bookmark is not shown.

Looks like the resulting query wants the tag to have filtered values at the same time:

spectacle zm8208

So I guess the main issue is that there is just one tag per row that can be compared. 

What works for me is to OR-connect the filters and filter again on the resulting tags by regexp… ``HAVING  (tags REGEXP 'tag1$' OR tags REGEXP 'tag1,') AND (tags REGEXP 'tag2$' OR tags REGEXP 'tag2,')`` but it feels like a very bad and ugly hack to make it work with the current from/join layout. Perhaps you've a better idea?

**Comment by marcelklehr** [comment]
Ah, gotcha. We could do a join for every tag to filter by, that's basically what the old implementation did (only with an EXISTS sub query). A join a day keeps the doctor away...

**Comment by blizzz** [comment]
Now phpunit started running amok for reasons… i created a seperate PR here https://github.com/nextcloud/bookmarks/pull/342 *fingers crossed*

**Comment by blizzz** [comment]
@marcelklehr could you rebase? the tests should succeed then.

**Comment by blizzz** [comment]
@marcelklehr awesome, thx! 🚀 

A sidenote: Github does not inform/notify about rebases, otherwise i would have seen and merged this earlier.

**Comment by marcelklehr** [comment]
:tada: yay!

ah, ok. sorry :)
