### PR TITLE
Fix export

### LINKED ISSUE #416: Export bookmarks doesn't work
### Steps to reproduce
1. click on gear
2. click export

### Expected behaviour
An htm file should be downloaded

### Actual behaviour
No file gets downloaded . This error message instead

> File not found
The specified document has not been found on the server.
You can click here to return to Nextcloud.

### Server configuration

**Operating system**:
debian stable

**Web server:**
nginx

**Database:**
mysql

**PHP version:**
7x

**Nextcloud version:** (see Nextcloud admin page)
12.0.4

**Bookmarks version:** (see Nextcloud apps page)
0.10.1  (v9.1.0RC4-314-g3be4e33a)
**Updated from an older Nextcloud or fresh install:**
fresh

### Note
I've already diagnosed the issue and made a fix. I'll submit PR right after this ticket

### PR DESCRIPTION
**Pull request by marcelklehr**
fixes #416 
(cherry picked from #417)

### CODE REVIEW

File: controller/rest/bookmarkcontroller.php [hunk 1]
```diff
@@ -396,9 +393,14 @@ public function importBookmark() {
...
 
 	/**
-	 * 
+	 * Hit this GET endpoint to export bookmarks via your API client.
+	 * http://server_ip/nextcloud/index.php/apps/bookmarks/public/rest/v2/bookmark/export
+	 * Basic authentication required.
 	 * @return \OCP\AppFramework\Http\Response
+	 *
 	 * @NoAdminRequired
+	 * @NoCSRFRequired
```
Comment (blizzz) [inline controller/rest/bookmarkcontroller.php]: that makes sense, but we should use the internal one, shouldn't we?

Comment (marcelklehr) [reply controller/rest/bookmarkcontroller.php]: I think the idea is to allow 3rd-party clients to export stuff as well (see https://github.com/nextcloud/bookmarks/pull/421/files#diff-0e033fd8797499a87a6bf2ffccef5c3cR43 where this is actually already in place)

**Review by blizzz — APPROVED** [review]
