### PR TITLE
Style fixes / grid view bookmark link

### LINKED ISSUE #1080: UI - "Home" covered by "Show sidebar" button
**Describe the bug**
I noticed this after the latest update. The two buttons share the same position.

Screenshot_1

**Desktop (please complete the following information):**
 - Browser Brave
 - Version 1.10.90 Chromium: 83.0.4103.97 (

### LINKED ISSUE #1082: Bookmarks not clickable
**Describe the bug**

In the bookmarks grid view it is not possible to open bookmarks by clicking them.

**To Reproduce**

1. Open the bookmarks app
2. Switch to the grid view
3. Click into the middle of a bookmark

**Expected behavior**
The bookmark opens.

**Actual behaviour**
Nothing

Note: it works with folders. If you click into the middle of a folder it navigates to the folder

**Screenshots**

click target

image

### PR DESCRIPTION
**Pull request by weeman1337**
* Fix the menu toggle position
* Fix some pixel misalignment in the breadcrumb bar
* Makes the entire bookmark behave like a link in grid view
* Tested on desktop and mobile
* Tested with Nextcloud 19 and 20

- closes #1080
- closes #1082 

image

### CODE REVIEW

File: src/components/Breadcrumbs.vue [hunk 1]
```diff
@@ -199,24 +199,10 @@ export default {
 </script>
 <style>
 .breadcrumbs {
-	padding: 2px 8px;
+	padding: 0 8px 0 44px;
 	display: flex;
-	position: fixed;
```
Comment (marcelklehr) [inline src/components/Breadcrumbs.vue:204]: I'd like to keep this, the breadcrumbs will be scrolled out of screen otherwise.

**Review by marcelklehr — CHANGES_REQUESTED** [review]

File: src/components/Breadcrumbs.vue (hunk 1 above)
Comment (weeman1337) [reply src/components/Breadcrumbs.vue:204]: Done. Required some more CSS frickeling, because `position: fixed;` was actually the point why it overlaps.

**Comment by weeman1337** [comment]
Additionally fixes the checkbox and "three dots" alignment:
image

**Comment by marcelklehr** [comment]
Awesome!

Can you also fix this while you're at it? My CSS skills seem to be too bad for this :/


image

File: src/components/Bookmark.vue [hunk 2]
```diff
@@ -11,6 +11,9 @@
 					? `linear-gradient(0deg, var(--color-main-background) 25%, rgba(0, 212, 255, 0) 50%), url('${imageUrl}')`
 					: undefined
 		}">
+		<a
```
Comment (weeman1337) [inline src/components/Bookmark.vue:14]: This makes the bookmark work like a link in grid view.

File: src/components/Bookmark.vue [hunk 3]
```diff
@@ -285,7 +289,25 @@ export default {
 	margin: 0;
 }
 
+.bookmark--gridview .bookmark__checkbox input[type="checkbox"].checkbox + label::before {
+	margin: 0 3px 3px 3px;
```
Comment (weeman1337) [inline src/components/Bookmark.vue:293]: Fixes the checkbox size. At the moment it has unequal white space.

File: src/components/Breadcrumbs.vue [hunk 4]
```diff
@@ -199,24 +199,14 @@ export default {
...
+	position: absolute;
```
Comment (weeman1337) [inline src/components/Breadcrumbs.vue:204]: I change the bookmark list to be scrollable instead of the entire app content.  
Now the menus on each side reduce the site of the entire app content.

- no overlapping
- left/right menu shift the content

File: src/components/Breadcrumbs.vue [hunk 5]
```diff
@@ -232,7 +222,7 @@ export default {
 .breadcrumbs__path > * {
 	display: inline-block;
 	height: 30px;
-	padding: 7px;
+	padding: 5px 7px;
```
Comment (weeman1337) [inline src/components/Breadcrumbs.vue:225]: Aligns the text

File: src/components/BookmarksList.vue [hunk 6]
```diff
@@ -101,6 +105,8 @@ export default {
 .bookmarkslist--gridview {
 	display: flex;
 	flex-flow: wrap;
+	gap: 10px;
```
Comment (weeman1337) [inline src/components/BookmarksList.vue:108]: Some grid view fine tuning

**Comment by weeman1337** [comment]
@marcelklehr please have another look.

File: src/components/BookmarksList.vue [hunk 7]
```diff
@@ -81,8 +81,12 @@ export default {
 </script>
 <style>
 .bookmarkslist {
+	/* 50px header; 50px breadcrumbs */
+	height: calc(100vh - 50px - 50px);
```
Comment (marcelklehr) [inline src/components/BookmarksList.vue:85]: Can you add `align-content: flex-start;` to fix spreading of content?

**Comment by marcelklehr** [comment]
Aaah, looks great. Thank you so much :)
